#include "stdafx.h"
#include "cCompositionRoot.h"
#include <Diplomacy/AllianceEnemyButtonProc.h>
#include <Diplomacy/AffinityTextProc.h>
#include <Warfare/cToolInvasionStrategy.h>
#include <Warfare/cPlanetAttackedEvent.h>

using namespace Simulator;

cCompositionRoot* cCompositionRoot::instance = nullptr;

/// AUTOGENERATED METHODS ///

int cCompositionRoot::AddRef() {
	return Simulator::cStrategy::AddRef();
}
int cCompositionRoot::Release() {
	return Simulator::cStrategy::Release();
}

const char* cCompositionRoot::GetName() const {
	return "SpaceDiplomacyOverhaul::cCompositionRoot";
}

bool cCompositionRoot::Write(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cCompositionRoot::Read(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cCompositionRoot::ATTRIBUTES[] ={
	// Add more attributes here
	// This one must always be at the end
	Simulator::Attribute()
};

void cCompositionRoot::Initialize(){
	instance = this;

	persistedEventSystem = nullptr;

	diplomacySystem = nullptr;
	diplomacyConfig = nullptr;
	persistedDiplomacyEventConfig = nullptr;
	archetypesConfig = nullptr;
	affinityConfig = nullptr;
	persistedDiplomacyEventManager = nullptr;

	archetypeAffinityModifier = nullptr;
	commonEnemyAffinityModifier = nullptr;
	commonAllyAffinityModifier = nullptr;
	warWithAllyAffinityModifier = nullptr;
	defeatedCommonEnemyAffinityModifier = nullptr;
	upliftedByMonolithAffinityModifier = nullptr;
	madePeaceAffinityModifier = nullptr;
	longPeaceAffinityModifier = nullptr;
	longAllianceAffinityModifier = nullptr;

	empireRelationsAnalyzer = nullptr;
	diplomacyEventDispatcher = nullptr;
	empireDiplomacyFactory = nullptr;
	diplomacyPopUpManager = nullptr;
	diplomacyEffectInfoProvider = nullptr;
	diplomacyEffectAnalyzer = nullptr;
	empireRelationshipController = nullptr;
	diplomacyEventListener = nullptr;
	affinityLayout = nullptr;

	warfareConfig = nullptr;
	spaceCombatMetrics = nullptr;
	archetypeStrengthConfig = nullptr;
	warfareStrengthAnalyzer = nullptr;
	warfareEventDispatcher = nullptr;
	empireWarfareFactory = nullptr;
	warfareEventListener = nullptr;

	PropertyListPtr configurationKeys;

	PropManager.GetPropertyList(id("ConfigurationKeys"), id("SdoConfig"), configurationKeys);

	App::Property::GetKey(configurationKeys.get(), 0x13741BB4, spacePopUpsTextsKey);
	App::Property::GetKey(configurationKeys.get(), 0x6FCEBDBF, diplomacyConfigKey);
	App::Property::GetKey(configurationKeys.get(), 0x57252EFE, archetypesAffinitiesKey);
	App::Property::GetKey(configurationKeys.get(), 0xE7AD6134, persistedDiplomacyEventConfigKey);
	App::Property::GetKey(configurationKeys.get(), 0x142ECBFA, archetypesAgressivitiesKey);
	App::Property::GetKey(configurationKeys.get(), 0x5598934F, affinityConfigKey);
	App::Property::GetKey(configurationKeys.get(), 0x76F0A8F2, popupsFilterConfigKey);
	App::Property::GetKey(configurationKeys.get(), 0x82AE7927, relationshipEffectsKey);
	App::Property::GetKey(configurationKeys.get(), 0xD96A8912, affinityTextConfigKey);

	App::Property::GetKey(configurationKeys.get(), 0x0FCF340F, warfareConfigKey);
	App::Property::GetKey(configurationKeys.get(), 0x9BD9B276, spaceCombatKey);
	App::Property::GetKey(configurationKeys.get(), 0xFC012E03, archetypeStrengthConfigKey);
}

void cCompositionRoot::Dispose(){
	
}

void cCompositionRoot::Update(int deltaTime, int deltaGameTime){
	
}



void cCompositionRoot::OnModeEntered(uint32_t previousModeID, uint32_t newModeID){
	if (newModeID == GameModeIDs::kGameSpace) {
		persistedEventSystem = cPersistedEventSystem::Get();

		diplomacyConfig = new cDiplomacyConfig(diplomacyConfigKey);

		archetypesConfig = new cArchetypesConfig(archetypesAffinitiesKey, archetypesAgressivitiesKey);

		persistedDiplomacyEventConfig = new cPersistedDiplomacyEventConfig(persistedDiplomacyEventConfigKey);

		affinityConfig = new cAffinityConfig(affinityConfigKey);

		persistedDiplomacyEventManager = new cPersistedDiplomacyEventManager(persistedDiplomacyEventConfig.get(), persistedEventSystem.get());

		archetypeAffinityModifier = new cArchetypeAffinityModifier();
		commonEnemyAffinityModifier = new cCommonEnemyAffinityModifier();
		commonAllyAffinityModifier = new cCommonAllyAffinityModifier();
		warWithAllyAffinityModifier = new cWarWithAllyAffinityModifier();
		defeatedCommonEnemyAffinityModifier = new cDefeatedCommonEnemyAffinityModifier();
		upliftedByMonolithAffinityModifier = new cUpliftedByMonolithAffinityModifier();
		madePeaceAffinityModifier = new cMadePeaceAffinityModifier();
		longPeaceAffinityModifier = new cLongPeaceAffinityModifier();
		longAllianceAffinityModifier = new cLongAllianceAffinityModifier();
		eastl::vector<IAffinityModifierPtr> affinityModifiers;
		affinityModifiers.push_back(archetypeAffinityModifier);
		affinityModifiers.push_back(commonEnemyAffinityModifier);
		affinityModifiers.push_back(commonAllyAffinityModifier);
		affinityModifiers.push_back(warWithAllyAffinityModifier);
		affinityModifiers.push_back(defeatedCommonEnemyAffinityModifier);
		affinityModifiers.push_back(upliftedByMonolithAffinityModifier);
		affinityModifiers.push_back(madePeaceAffinityModifier);
		affinityModifiers.push_back(longPeaceAffinityModifier);
		affinityModifiers.push_back(longAllianceAffinityModifier);

		empireRelationsAnalyzer = new cEmpireRelationsAnalyzer(diplomacyConfig.get(), archetypesConfig.get(), affinityConfig.get(), persistedDiplomacyEventManager.get(), affinityModifiers);

		diplomacyEventDispatcher = new cDiplomacyEventDispatcher();

		empireDiplomacyFactory = new cEmpireDiplomacyFactory(diplomacyConfig.get(), empireRelationsAnalyzer.get(), diplomacyEventDispatcher.get());

		diplomacySystem = cDiplomacySystem::Get();

		diplomacySystem->InjectDependencies(empireDiplomacyFactory.get());

		diplomacyPopUpManager = new cDiplomacyPopupManager(spacePopUpsTextsKey, popupsFilterConfigKey);

		diplomacyEffectInfoProvider = new cDiplomacyEffectInfoProvider(relationshipEffectsKey);

		diplomacyEffectAnalyzer = new cDiplomacyEffectAnalyzer(diplomacyEffectInfoProvider.get());

		empireRelationshipController = new cEmpireRelationshipController(diplomacyEffectAnalyzer.get());

		diplomacyEventListener = new cDiplomacyEventListener(diplomacyPopUpManager.get(), empireRelationshipController.get());

		MessageManager.AddListener(diplomacyEventListener.get(), cDiplomacyEvent::ID);

		// Add the AllianceEnemyButtonProc to the allies button.
		UILayoutPtr globalUiLayout = SimulatorSpaceGame.GetUI()->mpGlobalUI->mpLayout;
		if (globalUiLayout != nullptr) {
			UTFWin::IWindow* window = globalUiLayout->FindWindowByID(0x02E1CBD7);
			AllianceEnemyButtonProc* proc = new AllianceEnemyButtonProc();
			window->AddWinProc(proc);
		}
		// Loads the affinity number layout, attaches it to the communications layout,
		// and creates the AffinityTextProc.
		affinityLayout = new UTFWin::UILayout();
		affinityLayout->LoadByID(0x7db34bf7); // layouts_atlas~!AffinityLayout.spui.

		UTFWin::IWindow* mainWindow = WindowManager.GetMainWindow();
		UTFWin::IWindow* commScreenWindow = mainWindow->FindWindowByID(0x0493AB00)->GetParent();
		affinityLayout->SetParentWindow(commScreenWindow);


		UTFWin::IWindow* affinityMainWindow = affinityLayout->FindWindowByID(0x434EB9AD);
		AffinityTextProc* affinityTextProc = new AffinityTextProc(affinityMainWindow, empireRelationsAnalyzer.get(), affinityTextConfigKey);
		affinityMainWindow->AddWinProc(affinityTextProc);

		warfareConfig = new cWarfareConfig(warfareConfigKey);

		spaceCombatMetrics = new cSpaceCombatMetrics(spaceCombatKey);

		archetypeStrengthConfig = new cArchetypeStrengthConfig(archetypeStrengthConfigKey, archetypesConfig.get());

		warfareStrengthAnalyzer = new cWarfareStrengthAnalyzer(warfareConfig.get(), spaceCombatMetrics.get(), archetypeStrengthConfig.get());

		warfareEventDispatcher = new cWarfareEventDispatcher();

		empireWarfareFactory = new cEmpireWarfareFactory(warfareConfig.get(), warfareStrengthAnalyzer.get(), warfareEventDispatcher.get());

		warfareSystem = cWarfareSystem::Get();

		warfareSystem->InjectDependencies(empireWarfareFactory.get());

		warfareEventListener = new cWarfareEventListener();

		MessageManager.AddListener(warfareEventListener.get(), cPlanetAttackedEvent::ID);
		cToolStrategy* toolStrategy = ToolManager.GetStrategy(cToolInvasionStrategy::TYPE);
		cToolInvasionStrategy* toolInvasionStrategy = static_cast<cToolInvasionStrategy*>(toolStrategy);
		if (toolInvasionStrategy) {
			toolInvasionStrategy->warfareStrengthAnalyzer = warfareStrengthAnalyzer;
			toolInvasionStrategy->warfareEventDispatcher = warfareEventDispatcher;
		}
	}
}

void cCompositionRoot::OnModeExited(uint32_t previousModeID, uint32_t newModeID){
	if (previousModeID == GameModeIDs::kGameSpace) {
		persistedEventSystem.reset();

		diplomacySystem.reset();
		diplomacyConfig.reset();
		archetypesConfig.reset();
		affinityConfig.reset();
		persistedDiplomacyEventConfig.reset();
		persistedDiplomacyEventManager.reset();
		archetypeAffinityModifier.reset();
		commonEnemyAffinityModifier.reset();
		commonAllyAffinityModifier.reset();
		warWithAllyAffinityModifier.reset();
		defeatedCommonEnemyAffinityModifier.reset();
		upliftedByMonolithAffinityModifier.reset();
		madePeaceAffinityModifier.reset();
		longPeaceAffinityModifier.reset();
		longAllianceAffinityModifier.reset();
		empireRelationsAnalyzer.reset();
		diplomacyEventDispatcher.reset();
		empireDiplomacyFactory.reset();
		diplomacyPopUpManager.reset();
		diplomacyEffectInfoProvider.reset();
		diplomacyEffectAnalyzer.reset();
		empireRelationshipController.reset();

		MessageManager.RemoveListener(diplomacyEventListener.get(), cDiplomacyEvent::ID);
		diplomacyEventListener.reset();

		delete affinityLayout;
		affinityLayout = nullptr;

		warfareSystem.reset();
		warfareConfig.reset();
		spaceCombatMetrics.reset();
		archetypeStrengthConfig.reset();
		warfareStrengthAnalyzer.reset();
		warfareEventDispatcher.reset();
		empireWarfareFactory.reset();

		MessageManager.RemoveListener(warfareEventListener.get(), cPlanetAttackedEvent::ID);
		warfareEventListener.reset();
		cToolStrategy* toolStrategy = ToolManager.GetStrategy(cToolInvasionStrategy::TYPE);
		cToolInvasionStrategy* toolInvasionStrategy = static_cast<cToolInvasionStrategy*>(toolStrategy);
		if (toolInvasionStrategy) {
			toolInvasionStrategy->warfareStrengthAnalyzer.reset();
			toolInvasionStrategy->warfareEventDispatcher.reset();
		}
	}
}

bool cCompositionRoot::WriteToXML(Simulator::XmlSerializer* xml){
	return true;
}

cCompositionRoot* cCompositionRoot::Get() {
	return instance;
}