#include "stdafx.h"
#include "cDatabaseManager.h"
using namespace Simulator;

cDatabaseManager* cDatabaseManager::instance = nullptr;

/// AUTOGENERATED METHODS ///

int cDatabaseManager::AddRef() {
	return Simulator::cStrategy::AddRef();
}
int cDatabaseManager::Release() {
	return Simulator::cStrategy::Release();
}

const char* cDatabaseManager::GetName() const {
	return "SpaceDiplomacyWarfareOverhaul::cDatabaseManager";
}

bool cDatabaseManager::Write(Simulator::ISerializerStream* stream)
{
	if (!IsSpaceGame() || readFailedPermanently)
	{
		return true;
	}
	if (!dependenciesInjected)
	{
		ModAPI::Log("Error: attempted to write persisted objects before dependencies were injected.");
		return false;
	}
	if (persistedObjectDB == nullptr)
	{
		if (!InitializeDB())
		{
			ModAPI::Log("Error initializing db.");
			return false;
		}
	}
	if (!persistedObjectDB->Open(IO::AccessFlags::Write, IO::CD::OpenAlways))
	{
		ModAPI::Log("Error opening db for Write.");
		return false;
	}
	auto it = persistedObjects.begin();
	while (it != persistedObjects.end())
	{
		cPersistedObject* persistedObject = it->get();
		if (persistedObject == nullptr)
		{
			it = persistedObjects.erase(it);
			continue;
		}
		ISerializerWriteStream* writeStream = nullptr;
		ResourceKey key = GetResourceKey(persistedObject);
		if (persistedObject->Valid())
		{
			if (persistedObject->GetInstanceID() == 0 && persistedObject->GetNounID() != cPersistenceState::NOUN_ID)
			{
				ModAPI::Log("Error: Object with type %u and instanceID = 0", key.typeID);
				continue;
			}
			if (!persistedObjectDB->OpenWriteStream(key, &writeStream, true))
			{
				ModAPI::Log("Error opening write stream for key %u %u %u.", key.instanceID, key.groupID, key.typeID);
				it++;
				continue;
			}
			if (!persistedObject->Write(writeStream))
			{
				ModAPI::Log("Error writing key %u %u %u.",
					key.instanceID, key.groupID, key.typeID);
			}
			persistedObjectDB->CloseWriteStream(writeStream);
			it++;
		}
		else
		{
			if (persistenceState.get() == it->get())
			{
				ModAPI::Log("Error: persistenceState became invalid.");
				persistenceState.reset();
			}
			persistedObjectDB->DeleteRecord(key);
			it = persistedObjects.erase(it);
		}
	}
	if (!persistedObjectDB->Flush())
	{
		ModAPI::Log("Error flushing db");
	}
	if (!persistedObjectDB->Close())
	{
		ModAPI::Log("Error closing db");
		return false;
	}
	return Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cDatabaseManager::Read(Simulator::ISerializerStream* stream)
{
	if (!readDB && !readFailedPermanently)
	{
		ReadDB();
	}
	return readDB && Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cDatabaseManager::ATTRIBUTES[] = {
	// Add more attributes here
	// This one must always be at the end
	Simulator::Attribute()
};

void cDatabaseManager::Initialize() {
	instance = this;

	PropertyListPtr databaseConfigProp;

	PropManager.GetPropertyList(id("DatabaseConfig"), id("SdoConfig"), databaseConfigProp);
	App::Property::GetString16(databaseConfigProp.get(), 0xE7BE410B, databaseName);
	App::Property::GetString16(databaseConfigProp.get(), 0xADB380C5, currentModVersion);

	persistenceInjector = nullptr;
	dependenciesInjected = false;
	persistenceState = nullptr;
	persistedObjectDB = nullptr;
	readDB = false;
	readFailedPermanently = false;
}

void cDatabaseManager::Dispose() {
	
}

void cDatabaseManager::Update(int deltaTime, int deltaGameTime) {
	if (IsSpaceGame() && persistenceState != nullptr) {
		persistenceState->IncrementSpaceTime(uint32_t (deltaTime));
	}
}

bool cDatabaseManager::WriteToXML(Simulator::XmlSerializer* xml)
{
	return true;
}

void cDatabaseManager::OnModeEntered(uint32_t previousModeID, uint32_t newModeID)
{
	if (newModeID == GameModeIDs::kGameSpace)
	{
		if (!readDB)
		{
			// For some reason, Read() does not execute sometimes when loading a save.
			ReadDB();
		}

	}
}

void cDatabaseManager::OnModeExited(uint32_t previousModeID, uint32_t newModeID)
{
	if (previousModeID == GameModeIDs::kGameSpace)
	{
		persistenceInjector.reset();
		dependenciesInjected = false;
		persistedObjects.clear();
		readDB = false;
		readFailedPermanently = false;
		persistenceState.reset();
		persistedObjectDB.reset();
	}
}


cDatabaseManager* cDatabaseManager::Get() {
	return instance;
}

void cDatabaseManager::InjectDependencies(cPersistenceInjector* persistenceInjector)
{
	this->persistenceInjector = persistenceInjector;
	dependenciesInjected = true;
	for (cPersistedObjectPtr persistedObject : persistedObjects)
	{
		persistenceInjector->InjectObjectDependencies(persistedObject.get());
	}
}

cPersistenceState* cDatabaseManager::GetPersistenceState()
{
	if (!IsSpaceGame())
	{
		return nullptr;
	}
	// If the db has not been read, try to read it. If it fails, try again. If it fails
	// again, set readFailedPermanently (this prevents writing to the db) but allow
	// the method to continue and return a valid persistenceState.
	if (!readFailedPermanently && !readDB && !ReadDB())
	{
		if (!ReadDB())
		{
			readFailedPermanently = true;
			ModAPI::Log("Error: Multiple attempts failed to read the database; proceeding without persistence");
		}
	}
	// If persistenceState is nullptr, no persistenceState existed in the database, so we create it.
	if (persistenceState == nullptr)
	{
		persistenceState = object_cast<cPersistenceState>(ClassManager.Create(cPersistenceState::NOUN_ID));
		persistenceState->SetInstanceID(0);
		persistenceState->SetModVersion(currentModVersion);
		persistedObjects.push_back(persistenceState);
	}
	return persistenceState.get();
}

void cDatabaseManager::GetPersistedObjectsOfType(eastl::vector<cPersistedObjectPtr>& out, uint32_t type, bool includeSubtypes)
{
	if (!dependenciesInjected)
	{
		return;
	}
	for (cPersistedObjectPtr persistedObject : persistedObjects)
	{
		if (persistedObject == nullptr || !persistedObject->Valid())
		{
			continue;
		}
		if (persistedObject->GetNounID() == type ||
			(includeSubtypes && persistedObject->Cast(type) != nullptr))
		{
			out.push_back(persistedObject);
		}
	}
}

cPersistedObject* cDatabaseManager::CreatePersistedObjectOfType(uint32_t type)
{
	// Try to create persistenceState if it doesn't exist.
	GetPersistenceState();
	if (persistenceState == nullptr || !dependenciesInjected || type == cPersistenceState::NOUN_ID)
	{
		return nullptr;
	}
	cPersistedObject* persistedObject = object_cast<cPersistedObject>(ClassManager.Create(type));
	if (persistedObject != nullptr)
	{
		persistedObject->SetInstanceID(persistenceState->GetNextInstanceID());
		persistenceInjector->InjectObjectDependencies(persistedObject);
		persistedObjects.push_back(persistedObject);
	}
	return persistedObject;
}

// TODO find other way to identify a savegame instead of using the player empire id.
uint32_t cDatabaseManager::GetSavegameIdentifier()
{
	if (!IsSpaceGame())
	{
		return 0;
	}
	return GetPlayerEmpireID();
}

ResourceKey cDatabaseManager::GetResourceKey(cPersistedObject* persistedObject)
{
	return ResourceKey(persistedObject->GetInstanceID(), persistedObject->GetNounID(), GetSavegameIdentifier());
}

bool cDatabaseManager::InitializeDB()
{
	eastl::string16 path = Resource::Paths::GetSaveArea(Resource::SaveAreaID::GamesGame0)->GetLocation() + databaseName;
	DatabasePackedFilePtr db = new Resource::DatabasePackedFile(path.c_str());
	if (db->Initialize())
	{
		persistedObjectDB = new SerializerDatabase(db.get());
		return true;
	}
	else
	{
		return false;
	}
}

bool cDatabaseManager::ReadDB()
{
	if (!IsSpaceGame())
	{
		return true;
	}
	if (persistedObjectDB == nullptr)
	{
		if (!InitializeDB())
		{
			ModAPI::Log("Error initializing db.");
			return false;
		}
	}
	persistedObjects.clear();
	// For some reason, opening it in read-only mode always fails.
	if (!persistedObjectDB->Open(IO::AccessFlags::ReadWrite, IO::CD::OpenAlways))
	{
		ModAPI::Log("Error opening db for ReadWrite.");
		return false;
	}
	eastl::vector<ResourceKey> keys;
	Resource::StandardFileFilter filter(ResourceKey::kWildcardID, GetSavegameIdentifier(), ResourceKey::kWildcardID);
	persistedObjectDB->GetKeyList(keys, &filter);
	for (const ResourceKey& key : keys)
	{
		cPersistedObjectPtr persistedObject = object_cast<cPersistedObject>(ClassManager.Create(key.typeID));
		if (persistedObject == nullptr)
		{
			continue;
		}
		ISerializerReadStream* readStream = nullptr;
		if (!persistedObjectDB->OpenReadStream(key, &readStream))
		{
			ModAPI::Log("Error opening read stream for key %u %u %u.", key.instanceID, key.groupID, key.typeID);
			continue;
		}
		bool success = persistedObject->Read(readStream);
		persistedObjectDB->CloseReadStream(readStream);

		if (!success)
		{
			ModAPI::Log("Error reading key %u %u %u.",
				key.instanceID, key.groupID, key.typeID);
			continue;
		}
		persistedObjects.push_back(persistedObject);
		if (dependenciesInjected)
		{
			persistenceInjector->InjectObjectDependencies(persistedObject.get());
		}

		// Save the persistenceState in its special attribute.
		if (persistenceState == nullptr && persistedObject->GetInstanceID() == 0 && persistedObject->GetNounID() == cPersistenceState::NOUN_ID)
		{
			persistenceState = object_cast<cPersistenceState>(persistedObject.get());
			if (persistenceState != nullptr && persistenceState->GetModVersion() != currentModVersion)
			{
				persistenceState->SetModVersion(currentModVersion);
			}
		}
	}
	if (!persistedObjectDB->Close())
	{
		ModAPI::Log("Error closing db.");
		return false;
	}
	readDB = true;
	return true;
}
