#include "stdafx.h"
#include "cPersistenceState.h"

/// AUTOGENERATED METHODS ///

size_t cPersistenceStateFactory::GetTypes(uint32_t* pDstTypes, size_t count) const {
	if (count >= 1) {
		pDstTypes[0] = cPersistenceState::NOUN_ID;
		return 1;
	}
	return 0;
}
Object* cPersistenceStateFactory::Create(uint32_t type, ICoreAllocator* pAllocator) {
	return new cPersistenceState();
}
const char* cPersistenceStateFactory::GetName(uint32_t type) const {
	return "cPersistenceState";
}


int cPersistenceState::AddRef() {
	return DefaultRefCounted::AddRef();
}
int cPersistenceState::Release() {
	return DefaultRefCounted::Release();
}

uint32_t cPersistenceState::GetNounID() const {
	return NOUN_ID;
}

void* cPersistenceState::Cast(uint32_t type) const {
	CLASS_CAST(cPersistenceState);
	PARENT_CAST(cPersistedObject);
	return nullptr;
}

bool cPersistenceState::Write(Simulator::ISerializerStream* stream)
{
	return cPersistedObject::Write(stream) && Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cPersistenceState::Read(Simulator::ISerializerStream* stream)
{
	bool success = cPersistedObject::Read(stream) && Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
	if (success)
	{
		
	}
	return success;
}

eastl::string16 cPersistenceState::GetModVersion() const
{
	return this->modVersion;
}

void cPersistenceState::SetModVersion(eastl::string16 modVersion)
{
	this->modVersion = modVersion;
}

uint32_t cPersistenceState::GetNextInstanceID()
{
	
	return nextInstanceID++;
}

uint32_t cPersistenceState::GetCurrentSpaceTime()
{
	return this->spaceStageTime;
}

void cPersistenceState::IncrementSpaceTime(uint32_t deltaTime)
{
	this->spaceStageTime += deltaTime;
}


/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cPersistenceState::ATTRIBUTES[] = {
	SimAttribute(cPersistenceState, modVersion, 0),
	SimAttribute(cPersistenceState, nextInstanceID, 1),
	SimAttribute(cPersistenceState, spaceStageTime, 2),
	Simulator::Attribute()
};