#include "stdafx.h"
#include "cPersistedObject.h"
#include "cPersistenceState.h"

/// AUTOGENERATED METHODS ///

size_t cPersistedObjectFactory::GetTypes(uint32_t* pDstTypes, size_t count) const {
	if (count >= 1) {
		pDstTypes[0] = cPersistedObject::NOUN_ID;
		return 1;
	}
	return 0;
}
Object* cPersistedObjectFactory::Create(uint32_t type, ICoreAllocator* pAllocator) {
	return new cPersistedObject();
}
const char* cPersistedObjectFactory::GetName(uint32_t type) const {
	return "cPersistedObject";
}


int cPersistedObject::AddRef() {
	return DefaultRefCounted::AddRef();
}
int cPersistedObject::Release() {
	return DefaultRefCounted::Release();
}

uint32_t cPersistedObject::GetNounID() const {
	return NOUN_ID;
}

void* cPersistedObject::Cast(uint32_t type) const {
	CLASS_CAST(cPersistedObject);
	//PARENT_CAST(Simulator::Object);
	return nullptr;
}

bool cPersistedObject::Write(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cPersistedObject::Read(Simulator::ISerializerStream* stream)
{
	bool success = Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
	this->destroyed = !success;
	return success;
}

bool cPersistedObject::ISimulatorSerializable_func18h()
{
	return true;
}

bool cPersistedObject::WriteToXML(Simulator::XmlSerializer*)
{
	return true;
}

uint32_t cPersistedObject::GetInstanceID() const
{
	return this->instanceID;
}

void cPersistedObject::SetInstanceID(uint32_t instanceID)
{
	this->instanceID = instanceID;
}

bool cPersistedObject::HasInjectedDependencies() const
{
	return this->dependenciesInjected;
}

void cPersistedObject::SetDependenciesInjected(bool dependenciesInjected)
{
	this->dependenciesInjected = dependenciesInjected;
}

void cPersistedObject::Destroy()
{
	this->destroyed = true;
}

bool cPersistedObject::Valid()
{
	return HasInjectedDependencies() && !this->destroyed && instanceID != UINT32_MAX;
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cPersistedObject::ATTRIBUTES[] = {
	SimAttribute(cPersistedObject, instanceID, 0),
	Simulator::Attribute()
};