#include "stdafx.h"
#include "cPersistedEventSystem.h"

using namespace Simulator;

cPersistedEventSystem* cPersistedEventSystem::instance = nullptr;

/// AUTOGENERATED METHODS ///

int cPersistedEventSystem::AddRef() {
	return Simulator::cStrategy::AddRef();
}
int cPersistedEventSystem::Release() {
	return Simulator::cStrategy::Release();
}

const char* cPersistedEventSystem::GetName() const {
	return "SpaceDiplomacyOverhaul::cPersistedEventSystem";
}

bool cPersistedEventSystem::Write(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cPersistedEventSystem::Read(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cPersistedEventSystem::ATTRIBUTES[] = {
	SimAttribute(cPersistedEventSystem, currentTime, 0),
	Simulator::Attribute()
};

void cPersistedEventSystem::Initialize() {
	instance = this;
	currentTime = 0;
	elapsedTime = 0;
	nextExpirationTime = 0xffffffff;
	nextEventToExpire = nullptr;

	PropertyListPtr eventSystemConfigProp;

	PropManager.GetPropertyList(id("PersistedEventSystemConfig"), id("SdoConfig"), eventSystemConfigProp);

	App::Property::GetInt32(eventSystemConfigProp.get(), 0xE0D36182, cycleInterval);
}

void cPersistedEventSystem::Dispose() {
	
}

void cPersistedEventSystem::Update(int deltaTime, int deltaGameTime) {
	if (IsSpaceGame()) {
		currentTime += deltaGameTime;
		elapsedTime += deltaGameTime;
		if (nextEventToExpire != nullptr && currentTime > nextExpirationTime) {
			ExpireNextEventToExpire();

		}
		if (elapsedTime > cycleInterval) {
			auto persistedEvents = GetData<cPersistedEvent>();
			for (cPersistedEventPtr persistedEvent : persistedEvents) {
				if (!persistedEvent->Valid()) {
					DeleteEvent(persistedEvent.get());
				}
			}
			elapsedTime = 0;
		}
	}
}

bool cPersistedEventSystem::WriteToXML(Simulator::XmlSerializer* xml){
	return true;
}

void cPersistedEventSystem::OnModeEntered(uint32_t previousModeID, uint32_t newModeID){
	if (newModeID == kGameSpace) {
		auto persistedEvents = GetData<cPersistedEvent>();
		for (cPersistedEventPtr persistedEvent : persistedEvents) {
			if (!persistedEvent->Valid()) {
				GameNounManager.DestroyInstance(persistedEvent.get());
			}
			else if (persistedEvent->Expires()) {
				AddPersistedEvent(persistedEvent.get());
			}
		}
	}
}

void cPersistedEventSystem::OnModeExited(uint32_t previousModeID, uint32_t newModeID){
	if (previousModeID == GameModeIDs::kGameSpace) {
		currentTime = 0;
		elapsedTime = 0;
		nextExpirationTime = 0xffffffff;
		nextEventToExpire = nullptr;
		expirableEvents.clear();
	}
}

cPersistedEventSystem* cPersistedEventSystem::Get() {
	return instance;
}

uint32_t cPersistedEventSystem::CurrentTime(){
	return currentTime;
}

void cPersistedEventSystem::GetPersistedEvents(eastl::vector<cPersistedEventPtr>& persistedEvents){
	auto dataPersistedEvents = GetDataByCast<cPersistedEvent>();
	for (auto dataPersistedEvent : dataPersistedEvents) {
		if (dataPersistedEvent->Valid()) {
			persistedEvents.push_back(dataPersistedEvent);
		}
		else {
			DeleteEvent(dataPersistedEvent.get());
		}
	}
}

void cPersistedEventSystem::AddPersistedEvent(cPersistedEvent* persistedEvent){
	if (persistedEvent->Expires()) {
		AddExpirablePersistedEvent(persistedEvent);
	}
}

void cPersistedEventSystem::DeleteEvent(cPersistedEvent* persistedEvent){
	if (persistedEvent->Expires()) {
		RemoveExpirableEvent(persistedEvent);
	}
	GameNounManager.DestroyInstance(persistedEvent);
}

void cPersistedEventSystem::UpdateExpirationTimeOfExpirableEvent(cPersistedEvent* expirableEvent, uint32_t newExpirationTime){
	expirableEvent->SetExpirationTime(newExpirationTime);
	if ((nextEventToExpire != nullptr && nextEventToExpire == expirableEvent) || newExpirationTime < nextExpirationTime) {
		RecalculateNextEventToExpire();
	}
}

void cPersistedEventSystem::RecalculateNextEventToExpire(){
	if (!expirableEvents.empty()) {
		nextEventToExpire = *eastl::min_element(
			expirableEvents.begin(),
			expirableEvents.end(),
			[](const cPersistedEventPtr& a, const cPersistedEventPtr& b)
			{
				return a->GetExpirationTime() < b->GetExpirationTime();
			}
		);
		nextExpirationTime = nextEventToExpire->GetExpirationTime();
	}
	else {
		nextEventToExpire = nullptr;
		nextExpirationTime = 0xffffffff;
	}
}

void cPersistedEventSystem::AddExpirablePersistedEvent(cPersistedEvent* expirableEvent){
	expirableEvents.push_back(expirableEvent);
	if (expirableEvent->GetExpirationTime() < nextExpirationTime) {
		nextExpirationTime = expirableEvent->GetExpirationTime();
		nextEventToExpire = expirableEvent;
	}
}

eastl::vector<cPersistedEventPtr>::iterator cPersistedEventSystem::FindExpirableEvent(cPersistedEvent* expirableEvent){
	return eastl::find_if(
		expirableEvents.begin(),
		expirableEvents.end(),
		[expirableEvent](const cPersistedEventPtr& ptr)
		{
			return ptr.get() == expirableEvent;
		}
	);
}

void cPersistedEventSystem::ExpireNextEventToExpire(){
	// TODO notify the expiration of the event.
	if (nextEventToExpire != nullptr){
		cPersistedEvent* event = nextEventToExpire.get();
		auto it = FindExpirableEvent(nextEventToExpire.get());
		if (it != expirableEvents.end()) {
			expirableEvents.erase(it);
			GameNounManager.DestroyInstance(event);
		}
	}
	RecalculateNextEventToExpire();
}

void cPersistedEventSystem::RemoveExpirableEvent(cPersistedEvent* expirableEvent){
	auto it = FindExpirableEvent(expirableEvent);
	if (it != expirableEvents.end()) {
		bool recalculateNextExpirableEvent = *it == nextEventToExpire;
		expirableEvents.erase(it);
		if (recalculateNextExpirableEvent) {
			RecalculateNextEventToExpire();
		}
	}
}
