#include "stdafx.h"
#include "cPersistedEventSystem.h"

using namespace Simulator;

cPersistedEventSystem* cPersistedEventSystem::instance = nullptr;

/// AUTOGENERATED METHODS ///

int cPersistedEventSystem::AddRef() {
	return Simulator::cStrategy::AddRef();
}
int cPersistedEventSystem::Release() {
	return Simulator::cStrategy::Release();
}

const char* cPersistedEventSystem::GetName() const {
	return "Ai_Empire_Diplomacy::cPersistedEventSystem";
}

bool cPersistedEventSystem::Write(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cPersistedEventSystem::Read(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cPersistedEventSystem::ATTRIBUTES[] = {
	// Add more attributes here
	// This one must always be at the end
	Simulator::Attribute()
};

void cPersistedEventSystem::Initialize() {
	instance = this;
}

void cPersistedEventSystem::Dispose() {
	
}

void cPersistedEventSystem::Update(int deltaTime, int deltaGameTime) {
	
}

bool cPersistedEventSystem::WriteToXML(Simulator::XmlSerializer* xml){
	return true;
}

void cPersistedEventSystem::OnModeEntered(uint32_t previousModeID, uint32_t newModeID){
}

void cPersistedEventSystem::OnModeExited(uint32_t previousModeID, uint32_t newModeID){
}

cPersistedEventSystem* cPersistedEventSystem::Get() {
	return instance;
}
