#include "stdafx.h"
#include "cPersistedEvent.h"

/// AUTOGENERATED METHODS ///

size_t cPersistedEventFactory::GetTypes(uint32_t* pDstTypes, size_t count) const {
	if (count >= 1) {
		pDstTypes[0] = cPersistedEvent::NOUN_ID;
		return 1;
	}
	return 0;
}
Object* cPersistedEventFactory::Create(uint32_t type, ICoreAllocator* pAllocator) {
	return new cPersistedEvent();
}
const char* cPersistedEventFactory::GetName(uint32_t type) const {
	return "SpaceDiplomacyOverhaul::cPersistedEvent";
}


int cPersistedEvent::AddRef() {
	return DefaultRefCounted::AddRef();
}
int cPersistedEvent::Release() {
	return DefaultRefCounted::Release();
}

uint32_t cPersistedEvent::GetCastID() const {
	return TYPE;
}
uint32_t cPersistedEvent::GetNounID() const {
	return NOUN_ID;
}

void* cPersistedEvent::Cast(uint32_t type) const {
	CLASS_CAST(cPersistedEvent);
	PARENT_CAST(cGameData);
	return nullptr;
}

bool cPersistedEvent::Write(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cPersistedEvent::Read(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cPersistedEvent::ATTRIBUTES[] = {
	SimAttribute(cPersistedEvent, expires, 0),
	SimAttribute(cPersistedEvent, creationTime, 1),
	SimAttribute(cPersistedEvent, expirationTime, 2),
	Simulator::Attribute()
};

bool cPersistedEvent::Valid() {
	return !IsDestroyed();
}

bool cPersistedEvent::Expires() {
	return expires;
}

void cPersistedEvent::SetExpires(bool decays) {
	this->expires = decays;
}

uint32_t cPersistedEvent::GetCreationTime() {
	return creationTime;
}

void cPersistedEvent::SetCreationTime(uint32_t creationTime) {
	this->creationTime = creationTime;
}

uint32_t cPersistedEvent::GetExpirationTime() {
	return expirationTime;
}

void cPersistedEvent::SetExpirationTime(uint32_t expirationTime) {
	this->expirationTime = expirationTime;
}

