#include "stdafx.h"
#include "cDefeatedEnemyTogetherEvent.h"
#include <Spore-Mod-Utils/Include/SporeModUtils.h>

using namespace SporeModUtils;
using namespace Simulator;

/// AUTOGENERATED METHODS ///

size_t cDefeatedEnemyTogetherEventFactory::GetTypes(uint32_t* pDstTypes, size_t count) const {
	if (count >= 1) {
		pDstTypes[0] = cDefeatedEnemyTogetherEvent::NOUN_ID;
		return 1;
	}
	return 0;
}
Object* cDefeatedEnemyTogetherEventFactory::Create(uint32_t type, ICoreAllocator* pAllocator) {
	return new cDefeatedEnemyTogetherEvent();
}
const char* cDefeatedEnemyTogetherEventFactory::GetName(uint32_t type) const {
	return "SpaceDiplomacyOverhaul::cDefeatedEnemyTogetherEvent";
}

uint32_t cDefeatedEnemyTogetherEvent::GetCastID() const {
	return TYPE;
}
uint32_t cDefeatedEnemyTogetherEvent::GetNounID() const {
	return NOUN_ID;
}

void* cDefeatedEnemyTogetherEvent::Cast(uint32_t type) const {
	CLASS_CAST(cDefeatedEnemyTogetherEvent);
	CLASS_CAST(cPersistedDiplomacyEvent);
	CLASS_CAST(cPersistedEvent);
	PARENT_CAST(cGameData);
	return nullptr;
}

bool cDefeatedEnemyTogetherEvent::Write(Simulator::ISerializerStream* stream)
{
	return cPersistedDiplomacyEvent::Write(stream) && Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cDefeatedEnemyTogetherEvent::Read(Simulator::ISerializerStream* stream)
{
	return cPersistedDiplomacyEvent::Read(stream) && Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cDefeatedEnemyTogetherEvent::ATTRIBUTES[] = {
	Simulator::Attribute()
};