#include "stdafx.h"
#include "cFormedAllianceEvent.h"
#include <Spore-Mod-Utils/Include/SporeModUtils.h>

using namespace SporeModUtils;
using namespace Simulator;

/// AUTOGENERATED METHODS ///

size_t cFormedAllianceEventFactory::GetTypes(uint32_t* pDstTypes, size_t count) const {
	if (count >= 1) {
		pDstTypes[0] = cFormedAllianceEvent::NOUN_ID;
		return 1;
	}
	return 0;
}
Object* cFormedAllianceEventFactory::Create(uint32_t type, ICoreAllocator* pAllocator) {
	return new cFormedAllianceEvent();
}
const char* cFormedAllianceEventFactory::GetName(uint32_t type) const {
	return "cFormedAllianceEvent";
}
uint32_t cFormedAllianceEvent::GetNounID() const {
	return NOUN_ID;
}

void* cFormedAllianceEvent::Cast(uint32_t type) const {
	CLASS_CAST(cFormedAllianceEvent);
	PARENT_CAST(cPersistedDiplomacyEvent);
	return nullptr;
}

bool cFormedAllianceEvent::Write(Simulator::ISerializerStream* stream)
{
	return cPersistedDiplomacyEvent::Write(stream) && Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cFormedAllianceEvent::Read(Simulator::ISerializerStream* stream)
{
	return cPersistedDiplomacyEvent::Read(stream) && Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
}

bool cFormedAllianceEvent::Valid()
{
	return cPersistedDiplomacyEvent::Valid() &&
		DiplomacyUtils::Alliance(empire1.get(), empire2.get());
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cFormedAllianceEvent::ATTRIBUTES[] = {
	Simulator::Attribute()
};