#include "stdafx.h"
#include "cMadePeaceEvent.h"
#include <Spore-Mod-Utils/Include/SporeModUtils.h>

using namespace SporeModUtils;
using namespace Simulator;

/// AUTOGENERATED METHODS ///

size_t cMadePeaceEventFactory::GetTypes(uint32_t* pDstTypes, size_t count) const {
	if (count >= 1) {
		pDstTypes[0] = cMadePeaceEvent::NOUN_ID;
		return 1;
	}
	return 0;
}
Object* cMadePeaceEventFactory::Create(uint32_t type, ICoreAllocator* pAllocator) {
	return new cMadePeaceEvent();
}
const char* cMadePeaceEventFactory::GetName(uint32_t type) const {
	return "cMadePeaceEvent";
}
uint32_t cMadePeaceEvent::GetNounID() const {
	return NOUN_ID;
}

void* cMadePeaceEvent::Cast(uint32_t type) const {
	CLASS_CAST(cMadePeaceEvent);
	PARENT_CAST(cPersistedDiplomacyEvent);
	return nullptr;
}

bool cMadePeaceEvent::Write(Simulator::ISerializerStream* stream)
{
	return cPersistedDiplomacyEvent::Write(stream) && Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cMadePeaceEvent::Read(Simulator::ISerializerStream* stream)
{
	return cPersistedDiplomacyEvent::Read(stream) && Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
}

bool cMadePeaceEvent::Valid()
{
	return cPersistedDiplomacyEvent::Valid() &&
		!DiplomacyUtils::War(empire1.get(), empire2.get());
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cMadePeaceEvent::ATTRIBUTES[] = {
	Simulator::Attribute()
};