#include "stdafx.h"
#include "cNeighborsInPeaceEvent.h"
#include <Spore-Mod-Utils/Include/SporeModUtils.h>

using namespace SporeModUtils;
using namespace Simulator;

/// AUTOGENERATED METHODS ///

size_t cNeighborsInPeaceEventFactory::GetTypes(uint32_t* pDstTypes, size_t count) const {
	if (count >= 1) {
		pDstTypes[0] = cNeighborsInPeaceEvent::NOUN_ID;
		return 1;
	}
	return 0;
}
Object* cNeighborsInPeaceEventFactory::Create(uint32_t type, ICoreAllocator* pAllocator) {
	return new cNeighborsInPeaceEvent();
}
const char* cNeighborsInPeaceEventFactory::GetName(uint32_t type) const {
	return "cNeighborsInPeaceEvent";
}
uint32_t cNeighborsInPeaceEvent::GetNounID() const {
	return NOUN_ID;
}

void* cNeighborsInPeaceEvent::Cast(uint32_t type) const {
	CLASS_CAST(cNeighborsInPeaceEvent);
	PARENT_CAST(cPersistedDiplomacyEvent);
	return nullptr;
}

bool cNeighborsInPeaceEvent::Write(Simulator::ISerializerStream* stream)
{
	return cPersistedDiplomacyEvent::Write(stream) && Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cNeighborsInPeaceEvent::Read(Simulator::ISerializerStream* stream)
{
	return cPersistedDiplomacyEvent::Read(stream) && Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
}

bool cNeighborsInPeaceEvent::Valid()
{
	return cPersistedDiplomacyEvent::Valid() && 
		!DiplomacyUtils::War(empire1.get(), empire2.get());
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cNeighborsInPeaceEvent::ATTRIBUTES[] = {
	Simulator::Attribute()
};