#include "stdafx.h"
#include "cPersistedDiplomacyEvent.h"
#include <Spore-Mod-Utils/Include/SporeModUtils.h>

using namespace SporeModUtils;
using namespace Simulator;

/// AUTOGENERATED METHODS ///

size_t cPersistedDiplomacyEventFactory::GetTypes(uint32_t* pDstTypes, size_t count) const {
	if (count >= 1) {
		pDstTypes[0] = cPersistedDiplomacyEvent::NOUN_ID;
		return 1;
	}
	return 0;
}
Object* cPersistedDiplomacyEventFactory::Create(uint32_t type, ICoreAllocator* pAllocator) {
	return new cPersistedDiplomacyEvent();
}
const char* cPersistedDiplomacyEventFactory::GetName(uint32_t type) const {
	return "cPersistedDiplomacyEvent";
}

uint32_t cPersistedDiplomacyEvent::GetNounID() const {
	return NOUN_ID;
}

void* cPersistedDiplomacyEvent::Cast(uint32_t type) const {
	CLASS_CAST(cPersistedDiplomacyEvent);
	PARENT_CAST(cPersistedEvent);
	return nullptr;
}

bool cPersistedDiplomacyEvent::Write(Simulator::ISerializerStream* stream)
{
	empire1ID = empire1->GetEmpireID();
	empire2ID = empire2->GetEmpireID();
	empireOrderImportantSerialization = uint32_t(empireOrderImportant);
	return cPersistedEvent::Write(stream) && Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cPersistedDiplomacyEvent::Read(Simulator::ISerializerStream* stream)
{
	bool success = cPersistedEvent::Read(stream) && Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
	if (success)
	{
		empire1 = StarManager.GetEmpire(empire1ID);
		empire2 = StarManager.GetEmpire(empire2ID);
		empireOrderImportant = bool(empireOrderImportantSerialization);
	}
	return success;
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cPersistedDiplomacyEvent::ATTRIBUTES[] = {

	SimAttribute(cPersistedDiplomacyEvent, empire1ID, 0),
	SimAttribute(cPersistedDiplomacyEvent, empire2ID, 1),
	SimAttribute(cPersistedDiplomacyEvent, empireOrderImportantSerialization, 2),
	Simulator::Attribute()
};

bool cPersistedDiplomacyEvent::Valid() {
	return cPersistedEvent::Valid() &&
		// Empires Are Valid
		simulationValidator->ValidEmpire(empire1.get(), true) &&
		simulationValidator->ValidEmpire(empire2.get(), true);
}

cEmpire* cPersistedDiplomacyEvent::GetEmpire1() const{
	return empire1.get();
}

void cPersistedDiplomacyEvent::SetEmpire1(cEmpire* empire1) {
	this->empire1 = empire1;
}

cEmpire* cPersistedDiplomacyEvent::GetEmpire2() const{
	return empire2.get();
}

void cPersistedDiplomacyEvent::SetEmpire2(cEmpire* empire2) {
	this->empire2 = empire2;
}

bool cPersistedDiplomacyEvent::IsEmpireOrderImportant() const
{
	return this->empireOrderImportant;
}

void cPersistedDiplomacyEvent::SetEmpireOrderImportant(bool empireOrderImportant)
{
	this->empireOrderImportant = empireOrderImportant;
}

void cPersistedDiplomacyEvent::InjectDiplomacyEventDependencies(cSimulationValidator* simulationValidator)
{
	this->simulationValidator = simulationValidator;
}
