#include "stdafx.h"
#include "cPersistedDiplomacyEventData.h"

/// AUTOGENERATED METHODS ///

size_t cPersistedDiplomacyEventDataFactory::GetTypes(uint32_t* pDstTypes, size_t count) const {
	if (count >= 1) {
		pDstTypes[0] = cPersistedDiplomacyEventData::NOUN_ID;
		return 1;
	}
	return 0;
}
Object* cPersistedDiplomacyEventDataFactory::Create(uint32_t type, ICoreAllocator* pAllocator) {
	return new cPersistedDiplomacyEventData();
}
const char* cPersistedDiplomacyEventDataFactory::GetName(uint32_t type) const {
	return "cPersistedDiplomacyEventData";
}


int cPersistedDiplomacyEventData::AddRef() {
	return DefaultRefCounted::AddRef();
}
int cPersistedDiplomacyEventData::Release() {
	return DefaultRefCounted::Release();
}

uint32_t cPersistedDiplomacyEventData::GetCastID() const {
	return TYPE;
}
uint32_t cPersistedDiplomacyEventData::GetNounID() const {
	return NOUN_ID;
}

void* cPersistedDiplomacyEventData::Cast(uint32_t type) const {
	CLASS_CAST(cPersistedDiplomacyEventData);
	PARENT_CAST(cGameData);
	return nullptr;
}

bool cPersistedDiplomacyEventData::Write(Simulator::ISerializerStream* stream)
{
	affinityModifierSerialization = uint32_t(affinityModifier);
	return Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cPersistedDiplomacyEventData::Read(Simulator::ISerializerStream* stream)
{
	bool ret = Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
	affinityModifier = AffinityModifier(affinityModifierSerialization);
	return ret;
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cPersistedDiplomacyEventData::ATTRIBUTES[] = {
	//SimAttribute(cPersistedDiplomacyEventData, affinityModifier, 1),
	SimAttribute(cPersistedDiplomacyEventData, affinityGain, 0),
	SimAttribute(cPersistedDiplomacyEventData, preventsWars, 1),
	SimAttribute(cPersistedDiplomacyEventData, affinityModifierSerialization, 2),
	Simulator::Attribute()
};

AffinityModifier cPersistedDiplomacyEventData::GetAffinityModifier() {
	return affinityModifier;
}

void cPersistedDiplomacyEventData::SetAffinityModifier(AffinityModifier affinityModifier) {
	this->affinityModifier = affinityModifier;
}

int cPersistedDiplomacyEventData::GetAffinityGain() {
	return affinityGain;
}

void cPersistedDiplomacyEventData::SetAffinityGain(int affinityGain) {
	this->affinityGain = affinityGain;
}

bool cPersistedDiplomacyEventData::PreventsWars() {
	return preventsWars;
}

void cPersistedDiplomacyEventData::SetPreventsWars(bool preventsWars) {
	this->preventsWars = preventsWars;
}