#include "stdafx.h"
#include "cPersistedDiplomacyEvent.h"
#include <Spore-Mod-Utils/Include/SporeModUtils.h>

using namespace SporeModUtils;
using namespace Simulator;

/// AUTOGENERATED METHODS ///

size_t cPersistedDiplomacyEventFactory::GetTypes(uint32_t* pDstTypes, size_t count) const {
	if (count >= 1) {
		pDstTypes[0] = cPersistedDiplomacyEvent::NOUN_ID;
		return 1;
	}
	return 0;
}
Object* cPersistedDiplomacyEventFactory::Create(uint32_t type, ICoreAllocator* pAllocator) {
	return new cPersistedDiplomacyEvent();
}
const char* cPersistedDiplomacyEventFactory::GetName(uint32_t type) const {
	return "cPersistedDiplomacyEvent";
}

uint32_t cPersistedDiplomacyEvent::GetCastID() const {
	return TYPE;
}
uint32_t cPersistedDiplomacyEvent::GetNounID() const {
	return NOUN_ID;
}

void* cPersistedDiplomacyEvent::Cast(uint32_t type) const {
	CLASS_CAST(cPersistedDiplomacyEvent);
	PARENT_CAST(cPersistedEvent);
	return nullptr;
}

bool cPersistedDiplomacyEvent::Write(Simulator::ISerializerStream* stream)
{
	empire1ID = empire1->GetEmpireID();
	empire2ID = empire2->GetEmpireID();
	serializationEventType = uint32_t(eventType);
	return cPersistedEvent::Write(stream) && Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cPersistedDiplomacyEvent::Read(Simulator::ISerializerStream* stream)
{
	bool ret = cPersistedEvent::Read(stream) && Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
	empire1 = StarManager.GetEmpire(empire1ID);
	empire2 = StarManager.GetEmpire(empire2ID);
	eventType = PersistedDiplomacyEventType(serializationEventType);
	return ret;
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cPersistedDiplomacyEvent::ATTRIBUTES[] = {

	SimAttribute(cPersistedDiplomacyEvent, empire1ID, 0),
	SimAttribute(cPersistedDiplomacyEvent, empire2ID, 1),
	SimAttribute(cPersistedDiplomacyEvent, serializationEventType, 2),
	Simulator::Attribute()
};

bool cPersistedDiplomacyEvent::Valid() {
	return cPersistedEvent::Valid() && EmpireUtils::ValidNpcEmpire(empire1.get(), true) && EmpireUtils::ValidNpcEmpire(empire2.get(), true);
}

cEmpire* cPersistedDiplomacyEvent::GetEmpire1() {
	return empire1.get();
}

void cPersistedDiplomacyEvent::SetEmpire1(cEmpire* empire1) {
	this->empire1 = empire1;
}

cEmpire* cPersistedDiplomacyEvent::GetEmpire2() {
	return empire2.get();
}

void cPersistedDiplomacyEvent::SetEmpire2(cEmpire* empire2) {
	this->empire2 = empire2;
}

PersistedDiplomacyEventType cPersistedDiplomacyEvent::GetEventType(){
	return eventType;
}

void cPersistedDiplomacyEvent::SetEventType(PersistedDiplomacyEventType eventType){
	this->eventType = eventType;
}
