#include "stdafx.h"
#include "cPreparingToDeclareWarEvent.h"
#include <Spore-Mod-Utils/Include/SporeModUtils.h>

using namespace SporeModUtils;
/// AUTOGENERATED METHODS ///

size_t cPreparingForWarEventFactory::GetTypes(uint32_t* pDstTypes, size_t count) const {
	if (count >= 1) {
		pDstTypes[0] = cPreparingToDeclareWarEvent::NOUN_ID;
		return 1;
	}
	return 0;
}
Object* cPreparingForWarEventFactory::Create(uint32_t type, ICoreAllocator* pAllocator) {
	return new cPreparingToDeclareWarEvent();
}
const char* cPreparingForWarEventFactory::GetName(uint32_t type) const {
	return "cPreparingToDeclareWarEvent";
}

uint32_t cPreparingToDeclareWarEvent::GetNounID() const {
	return NOUN_ID;
}

void* cPreparingToDeclareWarEvent::Cast(uint32_t type) const {
	CLASS_CAST(cPreparingToDeclareWarEvent);
	PARENT_CAST(cPersistedDiplomacyEvent);
	return nullptr;
}

bool cPreparingToDeclareWarEvent::Write(Simulator::ISerializerStream* stream)
{
	return cPersistedDiplomacyEvent::Write(stream) && Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cPreparingToDeclareWarEvent::Read(Simulator::ISerializerStream* stream)
{
	return cPersistedDiplomacyEvent::Read(stream) && Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
}

bool cPreparingToDeclareWarEvent::Valid()
{
	return cPersistedDiplomacyEvent::Valid() &&
		!DiplomacyUtils::War(empire1.get(), empire2.get()) &&
		(diplomacyConfig->GetStartsWarsWhileAtWar() ||
		empire1->mEnemies.empty());
}

void cPreparingToDeclareWarEvent::InjectPreparingToDeclareWarEventDependencies(cDiplomacyConfig* diplomacyConfig)
{
	this->diplomacyConfig = diplomacyConfig;
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cPreparingToDeclareWarEvent::ATTRIBUTES[] = {
	// Add more attributes here
	// This one must always be at the end
	Simulator::Attribute()
};