#include "stdafx.h"
#include "cUpliftedByMonolithEvent.h"

/// AUTOGENERATED METHODS ///

size_t cUpliftedByMonolithEventFactory::GetTypes(uint32_t* pDstTypes, size_t count) const {
	if (count >= 1) {
		pDstTypes[0] = cUpliftedByMonolithEvent::NOUN_ID;
		return 1;
	}
	return 0;
}
Object* cUpliftedByMonolithEventFactory::Create(uint32_t type, ICoreAllocator* pAllocator) {
	return new cUpliftedByMonolithEvent();
}
const char* cUpliftedByMonolithEventFactory::GetName(uint32_t type) const {
	return "SpaceDiplomacyOverhaul::cUpliftedByMonolithEvent";
}

uint32_t cUpliftedByMonolithEvent::GetCastID() const {
	return TYPE;
}
uint32_t cUpliftedByMonolithEvent::GetNounID() const {
	return NOUN_ID;
}

void* cUpliftedByMonolithEvent::Cast(uint32_t type) const {
	CLASS_CAST(cUpliftedByMonolithEvent);
	CLASS_CAST(cPersistedDiplomacyEvent);
	CLASS_CAST(cPersistedEvent);
	PARENT_CAST(cGameData);
	return nullptr;
}

bool cUpliftedByMonolithEvent::Write(Simulator::ISerializerStream* stream)
{
	return cPersistedDiplomacyEvent::Write(stream) && Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cUpliftedByMonolithEvent::Read(Simulator::ISerializerStream* stream)
{
	return cPersistedDiplomacyEvent::Read(stream) && Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cUpliftedByMonolithEvent::ATTRIBUTES[] = {
	Simulator::Attribute()
};