#include "stdafx.h"
#include "cDiplomacySystem.h"
#include <Spore/Simulator/ConversationResource.h>
#include <Spore/Simulator/SubSystem/CommManager.h>
#include <Spore-Mod-Utils/Include/SporeModUtils.h>

using namespace SporeModUtils;
using namespace Simulator;

cDiplomacySystem* cDiplomacySystem::instance = nullptr;


/// AUTOGENERATED METHODS ///

int cDiplomacySystem::AddRef() {
	return Simulator::cStrategy::AddRef();
}
int cDiplomacySystem::Release() {
	return Simulator::cStrategy::Release();
}

const char* cDiplomacySystem::GetName() const {
	return "SpaceDiplomacyOverhaul::cDiplomacySystem";
}

bool cDiplomacySystem::Write(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cDiplomacySystem::Read(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cDiplomacySystem::ATTRIBUTES[] = {

	Simulator::Attribute()
};


void cDiplomacySystem::Initialize() {
	instance = this;
	ready = false;
	cycle = 0;

	PropertyListPtr managerConfigProp;

	PropManager.GetPropertyList(id("ManagerConfig"), id("SdoConfig"), managerConfigProp);

	App::Property::GetFloat(managerConfigProp.get(), 0x0D00F9E5, activeRadius);
	App::Property::GetInt32(managerConfigProp.get(), 0x9EC13ACD, minSubcycleStep);
	App::Property::GetInt32(managerConfigProp.get(), 0xB5BD28BA, cycleInterval);

	empireDiplomacyFactory = nullptr;
	elapsedTime = 0;
	subcycleStep = 0;
	empiresPerSubCycle = 0;
	nextSubcycleTime = 0;
	cycle = 0;
}

void cDiplomacySystem::Dispose() {


}

void cDiplomacySystem::Update(int deltaTime, int deltaGameTime) {
	if (IsSpaceGame() && ready) {
		elapsedTime += deltaGameTime;
		if (elapsedTime > cycleInterval) {
			StartDiplomacyCycle();
			cycle++;
		}
		// Start of a subcycle.
		while (elapsedTime > nextSubcycleTime) {
			DiplomacySubCycle();
			nextSubcycleTime += subcycleStep;
		}
	}
}

void cDiplomacySystem::OnModeEntered(uint32_t previousModeID, uint32_t newModeID) {
	if (newModeID == GameModeIDs::kGameSpace) {
		empiresDiplomacy.clear();

		// Randomizes the start of the first cycle to avoid being synchronized with the cycles of other managers.
		elapsedTime = Math::rand(cycleInterval / 2);
		nextSubcycleTime = 9999999;
		cycle = 0;
	}
}

void cDiplomacySystem::OnModeExited(uint32_t previousModeID, uint32_t newModeID) {
	if (previousModeID == GameModeIDs::kGameSpace) {

		empiresDiplomacy.clear();
		empireDiplomacyFactory.reset();
		ready = false;
	}
}

bool cDiplomacySystem::WriteToXML(XmlSerializer*)
{
	return true;
}

cDiplomacySystem* cDiplomacySystem::Get() {
	return instance;
}

void cDiplomacySystem::InjectDependencies(cEmpireDiplomacyFactory* empireDiplomacyFactory){
	this->empireDiplomacyFactory = empireDiplomacyFactory;
	ready = true;
}

void cDiplomacySystem::DiplomacySubCycle() {
	if (empireToManage != empiresDiplomacy.end()) {
		if (EmpireUtils::ValidNpcEmpire(empireToManage->get()->empire.get())) {
			empireToManage->get()->ManageDiplomacy();
		}
		++empireToManage;
	}
}

void cDiplomacySystem::StartDiplomacyCycle() {
	empiresDiplomacy.clear();

	eastl::vector<cEmpirePtr> empires;
	EmpireUtils::GetEmpiresInRadius(GetPlayerHomePlanet()->GetStarRecord()->mPosition, activeRadius, empires);
	for (cEmpirePtr empire : empires) {
		if (EmpireUtils::ValidNpcEmpire(empire.get())) {
			cEmpireDiplomacyPtr empireDiplomacy = empireDiplomacyFactory->CreateEmpireDiplomacy(empire.get());
			empiresDiplomacy.push_back(empireDiplomacy);
		}
	}

	empireToManage = empiresDiplomacy.begin();
	int numEmpires = empiresDiplomacy.size();
	int calculatedStep = cycleInterval / (numEmpires + 1);
	subcycleStep = max(calculatedStep, minSubcycleStep);
	// substract subcycleStep because the first subcycle is at subcycleStep miliseconds.
	int numSubcycles = cycleInterval / subcycleStep;
	// Division rounding up.
	empiresPerSubCycle = (numEmpires + numSubcycles - 1) / (numSubcycles);
	elapsedTime = 0;
	nextSubcycleTime = subcycleStep;
}