#include "stdafx.h"
#include "cPersistedDiplomacyEvent.h"

/// AUTOGENERATED METHODS ///

size_t cPersistedDiplomacyEventFactory::GetTypes(uint32_t* pDstTypes, size_t count) const {
	if (count >= 1) {
		pDstTypes[0] = cPersistedDiplomacyEvent::NOUN_ID;
		return 1;
	}
	return 0;
}
Object* cPersistedDiplomacyEventFactory::Create(uint32_t type, ICoreAllocator* pAllocator) {
	return new cPersistedDiplomacyEvent();
}
const char* cPersistedDiplomacyEventFactory::GetName(uint32_t type) const {
	return "cPersistedDiplomacyEvent";
}

uint32_t cPersistedDiplomacyEvent::GetCastID() const {
	return TYPE;
}
uint32_t cPersistedDiplomacyEvent::GetNounID() const {
	return NOUN_ID;
}

void* cPersistedDiplomacyEvent::Cast(uint32_t type) const {
	CLASS_CAST(cPersistedDiplomacyEvent);
	PARENT_CAST(cPersistedEvent);
	return nullptr;
}

bool cPersistedDiplomacyEvent::Write(Simulator::ISerializerStream* stream)
{
	return cPersistedEvent::Write(stream) && Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cPersistedDiplomacyEvent::Read(Simulator::ISerializerStream* stream)
{
	return cPersistedEvent::Read(stream) && Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cPersistedDiplomacyEvent::ATTRIBUTES[] = {

	SimAttribute(cPersistedDiplomacyEvent, empire1ID, 1),
	SimAttribute(cPersistedDiplomacyEvent, empire2ID, 1),
	Simulator::Attribute()
};

uint32_t cPersistedDiplomacyEvent::GetEmpire1ID() {
	return empire1ID;
}

void cPersistedDiplomacyEvent::SetEmpire1ID(uint32_t ID) {
	empire1ID = ID;
}

uint32_t cPersistedDiplomacyEvent::GetEmpire2ID() {
	return empire2ID;
}

void cPersistedDiplomacyEvent::SetEmpire2ID(uint32_t ID) {
	empire2ID = ID;
}