#include "stdafx.h"
#include "cPersistedAffinityEvent.h"

/// AUTOGENERATED METHODS ///

size_t cPersistedAffinityEventFactory::GetTypes(uint32_t* pDstTypes, size_t count) const {
	if (count >= 1) {
		pDstTypes[0] = cPersistedAffinityEvent::NOUN_ID;
		return 1;
	}
	return 0;
}
Object* cPersistedAffinityEventFactory::Create(uint32_t type, ICoreAllocator* pAllocator) {
	return new cPersistedAffinityEvent();
}
const char* cPersistedAffinityEventFactory::GetName(uint32_t type) const {
	return "cPersistedAffinityEvent";
}

uint32_t cPersistedAffinityEvent::GetCastID() const {
	return TYPE;
}
uint32_t cPersistedAffinityEvent::GetNounID() const {
	return NOUN_ID;
}

void* cPersistedAffinityEvent::Cast(uint32_t type) const {
	CLASS_CAST(cPersistedAffinityEvent);
	PARENT_CAST(cPersistedDiplomacyEvent);
	return nullptr;
}

bool cPersistedAffinityEvent::Write(Simulator::ISerializerStream* stream)
{
	return cPersistedDiplomacyEvent::Write(stream) && Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cPersistedAffinityEvent::Read(Simulator::ISerializerStream* stream)
{
	return cPersistedDiplomacyEvent::Read(stream) && Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cPersistedAffinityEvent::ATTRIBUTES[] = {
	// Add more attributes here
	// This one must always be at the end
	Simulator::Attribute()
};