#include "stdafx.h"
#include "cDiplomacySystem.h"
#include <Spore/Simulator/ConversationResource.h>
#include <Spore/Simulator/SubSystem/CommManager.h>
#include "Spore-Mod-Utils/Include/SporeModUtils.h"
#include <AllianceEnemyButtonProc.h>
#include <cDiplomacyEvent.h>

using namespace SporeModUtils;
using namespace Simulator;

cDiplomacySystem* cDiplomacySystem::instance = nullptr;


/// AUTOGENERATED METHODS ///

int cDiplomacySystem::AddRef() {
	return Simulator::cStrategy::AddRef();
}
int cDiplomacySystem::Release() {
	return Simulator::cStrategy::Release();
}

const char* cDiplomacySystem::GetName() const {
	return "HarderSpaceDiplomacy::cDiplomacySystem";
}

bool cDiplomacySystem::Write(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cDiplomacySystem::Read(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cDiplomacySystem::ATTRIBUTES[] = {
	// Add more attributes here
	// This one must always be at the end
	Simulator::Attribute()
};


void cDiplomacySystem::Initialize() {
	activeRadius = 30;
	cycle = 0;
	instance = this;
	diplomacyConfig = nullptr;
	archetypesAffinities = nullptr;
	empireRelationsAnalyzer = nullptr;
	diplomacyEventDispatcher = nullptr;
	diplomacyEventListener = new cDiplomacyEventListener();
	MessageManager.AddListener(diplomacyEventListener.get(), cDiplomacyEvent::ID);

	PropertyListPtr managerConfigProp;

	PropManager.GetPropertyList(id("ManagerConfig"), id("SdoConfig"), managerConfigProp);

	App::Property::GetInt32(managerConfigProp.get(), 0xB5BD28BA, cycleInterval);
	App::Property::GetKey(managerConfigProp.get(), 0x6FCEBDBF, diplomacyConfigKey);
	App::Property::GetKey(managerConfigProp.get(), 0x57252EFE, archetypesAffinitiesKey);
}

void cDiplomacySystem::Dispose() {


}

void cDiplomacySystem::Update(int deltaTime, int deltaGameTime) {
	if (IsSpaceGame()) {
		elapsedTime += deltaGameTime;
		if (elapsedTime > cycleInterval) {
			EmpireDiplomacyCycle();
			elapsedTime = 0;
			cycle++;
			App::ConsolePrintF("cycle: %d", cycle);
		}
	}
}

void cDiplomacySystem::OnModeEntered(uint32_t previousModeID, uint32_t newModeID) {
	if (newModeID == GameModeIDs::kGameSpace) {
		diplomacyConfig = new cDiplomacyConfig(diplomacyConfigKey);
		archetypesAffinities = new cArchetypesAffinities(archetypesAffinitiesKey);
		empireRelationsAnalyzer = new cEmpireRelationsAnalyzer(diplomacyConfig.get(), archetypesAffinities.get());
		diplomacyEventDispatcher = new cDiplomacyEventDispatcher();
		empiresDiplomacy.clear();

		cycle = 0;
		elapsedTime = 0;
		UILayoutPtr globalUiLayout = SimulatorSpaceGame.GetUI()->mpGlobalUI->mpLayout;
		if (globalUiLayout != nullptr) {
			UTFWin::IWindow* window = globalUiLayout->FindWindowByID(0x02E1CBD7);
			AllianceEnemyButtonProc* proc = new AllianceEnemyButtonProc();
			window->AddWinProc(proc);
		}
	}
}

void cDiplomacySystem::OnModeExited(uint32_t previousModeID, uint32_t newModeID) {
	if (previousModeID == GameModeIDs::kGameSpace) {
		diplomacyConfig.reset();
		archetypesAffinities.reset();
		empireRelationsAnalyzer.reset();
		diplomacyEventDispatcher.reset();
		empiresDiplomacy.clear();
	}
}

bool cDiplomacySystem::WriteToXML(XmlSerializer*)
{
	return true;
}

cDiplomacySystem* cDiplomacySystem::Get() {
	return instance;
}

eastl::string16 cDiplomacySystem::ArchetypeToString(Archetypes archetype) {
	switch (archetype) {
	case kArchetypeWarrior: case kArchetypePlayerWarrior: return u"Warrior";
	case kArchetypeTrader: case kArchetypePlayerTrader: return u"Trader";
	case kArchetypeScientist: case kArchetypePlayerScientist: return u"Scientist";
	case kArchetypeShaman: case kArchetypePlayerShaman: return u"Shaman";
	case kArchetypeBard: case kArchetypePlayerBard: return u"Bard";
	case kArchetypeZealot: case kArchetypePlayerZealot: return u"Zealot";
	case kArchetypeDiplomat: case kArchetypePlayerDiplomat: return u"Diplomat";
	case kArchetypeEcologist: case kArchetypePlayerEcologist: return u"Ecologist";
	case kArchetypeGrob: return u"Grob";
	case kArchetypePlayerWanderer: return u"Wanderer";
	case kArchetypePlayerKnight: return u"Knight";
	default: return u"Unknown";
	}
}

void cDiplomacySystem::GetEmpiresInDiplomaticRange(cEmpire* empire, eastl::vector<cEmpirePtr>& empires) {
	//float range = GetEmpireDiplomaticRange(empire);
	//EmpireUtils::GetEmpiresInRangeOfEmpire(empire, range, empires, true);
}


void  cDiplomacySystem::CreateTributeComm(cEmpire* empire) {
	CnvAction action;
	action.actionID = 0x4C182387;
	//when the relation is blue face or better this doesn´t work
	CommManager.HandleSpaceCommAction(action, empire->GetEmpireID(), empire->RequireHomePlanet()->GetID(), nullptr); 
}

void cDiplomacySystem::ManageEmpireDiplomacy(cEmpire* empire) {

}

void cDiplomacySystem::EmpireDiplomacyCycle() {
	empiresDiplomacy.clear();
	eastl::vector<cEmpirePtr> empires;
	EmpireUtils::GetEmpiresInRadius(GetActiveStarRecord()->mPosition, activeRadius, empires);
	for (cEmpirePtr empire : empires) {
		if (EmpireUtils::ValidNpcEmpire(empire.get())) {
			cEmpireDiplomacyPtr empireDiplomacy = new cEmpireDiplomacy(empire.get(), diplomacyConfig.get(), empireRelationsAnalyzer.get(), diplomacyEventDispatcher.get());
			empiresDiplomacy.push_back(empireDiplomacy);
		}
	}
	// TODO the alliance strenght.
	for (cEmpireDiplomacyPtr empireDiplomacy : empiresDiplomacy) {
		if (EmpireUtils::ValidNpcEmpire(empireDiplomacy->empire.get())) {
			empireDiplomacy->ManageDiplomacy();
		}
	}
}