#include "stdafx.h"
#include "cEmpireDiplomacyManager.h"
#include <Spore/Simulator/ConversationResource.h>
#include <Spore/Simulator/SubSystem/CommManager.h>
#include "Spore-Mod-Utils/Include/SporeModUtils.h"
#include <AllianceEnemyButtonProc.h>

using namespace SporeModUtils;

cEmpireDiplomacyManager* cEmpireDiplomacyManager::instance = nullptr;


/// AUTOGENERATED METHODS ///

int cEmpireDiplomacyManager::AddRef() {
	return Simulator::cStrategy::AddRef();
}
int cEmpireDiplomacyManager::Release() {
	return Simulator::cStrategy::Release();
}

const char* cEmpireDiplomacyManager::GetName() const {
	return "HarderSpaceDiplomacy::cEmpireDiplomacyManager";
}

bool cEmpireDiplomacyManager::Write(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cEmpireDiplomacyManager::Read(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cEmpireDiplomacyManager::ATTRIBUTES[] = {
	// Add more attributes here
	// This one must always be at the end
	Simulator::Attribute()
};


void cEmpireDiplomacyManager::Initialize() {
	activeRadius = 30;
	cycle = 0;
	instance = this;

	PropertyListPtr generalConfiguration;

	PropManager.GetPropertyList(id("Config"), id("SdoConfig"), generalConfiguration);

	App::Property::GetInt32(generalConfiguration.get(), 0xB5BD28BA, cycleInterval);

	App::Property::GetArrayFloat(generalConfiguration.get(), 0xE9F5A508, diplomacyRange);

	App::Property::GetInt32(generalConfiguration.get(), 0x74F51B4B, maxAffinitySoftCap);

	App::Property::GetInt32(generalConfiguration.get(), 0x63812B01, minAffinitySoftCap);

	App::Property::GetFloat(generalConfiguration.get(), 0x38D9CD5F, maxAllianceProbability);

	App::Property::GetFloat(generalConfiguration.get(), 0xDCFF754A, maxWarProbability);

	App::Property::GetInt32(generalConfiguration.get(), 0xDB025009, affinityThresholdForStableAlliance);

	App::Property::GetInt32(generalConfiguration.get(), 0x07DB4B1C, affinityThresholdForUnstableAlliance);

	App::Property::GetInt32(generalConfiguration.get(), 0x22472FA3, affinityThresholdForWar);

	App::Property::GetInt32(generalConfiguration.get(), 0xECC06D76, affinityGainForAllyOfAlly);

	App::Property::GetInt32(generalConfiguration.get(), 0xC595B63C, affinityGainForEnemyOfEnemy);

	App::Property::GetInt32(generalConfiguration.get(), 0x21D306E2, affinityGainForEnemyOfAlly);

	App::Property::GetArrayInt32(generalConfiguration.get(), 0x8DA36269, baseAggressivityByArchetype);

	App::Property::GetArrayInt32(generalConfiguration.get(), 0x51A5A369, aggressivityGrowthByPowerLevel);

	App::Property::GetBool(generalConfiguration.get(), 0xC1C6CE47, autoDeclareWarOnAllyEnemies);

	App::Property::GetBool(generalConfiguration.get(), 0xCC04E149, startsWarsWhileAtWar);

	App::Property::GetFloat(generalConfiguration.get(), 0x4BB58401, powerThresholdToAvoidWar);

	PropertyListPtr archetypesAfinitiesConfig;

	PropManager.GetPropertyList(id("ArchetypeAffinities"), id("SdoConfig"), archetypesAfinitiesConfig);
	
	uint32_t compatibilitesHash[8] = { 0x36F42279, 0x70C32FF1, 0x9526B215, 0xC225B633, 0xDD439F1C, 0x51DEC400, 0xCC6B3EFB, 0xD2A58F42 };

	for (int i = 0; i < 8; i++) {
		eastl::vector<int> affinity;
		App::Property::GetArrayInt32(archetypesAfinitiesConfig.get(), compatibilitesHash[i], affinity);
		archetypesAffinities.push_back(affinity);
	}
}

void cEmpireDiplomacyManager::Dispose() {


}

void cEmpireDiplomacyManager::Update(int deltaTime, int deltaGameTime) {
	if (IsSpaceGame()) {
		elapsedTime += deltaGameTime;
		if (elapsedTime > cycleInterval) {
			EmpireDiplomacyCycle();
			elapsedTime = 0;
			cycle++;
			App::ConsolePrintF("cycle: %d", cycle);
		}
	}
}

void cEmpireDiplomacyManager::OnModeEntered(uint32_t previousModeID, uint32_t newModeID) {
	if (newModeID == GameModeIDs::kGameSpace) {
		cycle = 0;
		elapsedTime = 0;
		UILayoutPtr globalUiLayout = SimulatorSpaceGame.GetUI()->mpGlobalUI->mpLayout;
		if (globalUiLayout != nullptr) {
			UTFWin::IWindow* window = globalUiLayout->FindWindowByID(0x02E1CBD7);
			AllianceEnemyButtonProc* proc = new AllianceEnemyButtonProc();
			window->AddWinProc(proc);
		}
	}
}

void cEmpireDiplomacyManager::OnModeExited(uint32_t previousModeID, uint32_t newModeID) {
	if (previousModeID == GameModeIDs::kGameSpace) {
		diplomaticProfiles.clear();
	}
}

bool cEmpireDiplomacyManager::WriteToXML(XmlSerializer*)
{
	return true;
}

cEmpireDiplomacyManager* cEmpireDiplomacyManager::Get() {
	return instance;
}

eastl::string16 cEmpireDiplomacyManager::ArchetypeToString(Archetypes archetype) {
	switch (archetype) {
		case kArchetypeWarrior: case kArchetypePlayerWarrior: return u"Warrior";
		case kArchetypeTrader: case kArchetypePlayerTrader: return u"Trader";
		case kArchetypeScientist: case kArchetypePlayerScientist: return u"Scientist";
		case kArchetypeShaman: case kArchetypePlayerShaman: return u"Shaman";
		case kArchetypeBard: case kArchetypePlayerBard: return u"Bard";
		case kArchetypeZealot: case kArchetypePlayerZealot: return u"Zealot";
		case kArchetypeDiplomat: case kArchetypePlayerDiplomat: return u"Diplomat";
		case kArchetypeEcologist: case kArchetypePlayerEcologist: return u"Ecologist";
		case kArchetypeGrob: return u"Grob";
		case kArchetypePlayerWanderer: return u"Wanderer";
		case kArchetypePlayerKnight: return u"Knight";
		default: return u"Unknown";
	}
}

float cEmpireDiplomacyManager::GetEmpireDiplomaticRange(cEmpire* empire) {
	int empireLevel = EmpireUtils::GetEmpireLevel(empire);
	return diplomacyRange[empireLevel];
}

void cEmpireDiplomacyManager::GetEmpiresInDiplomaticRange(cEmpire* empire, eastl::vector<cEmpirePtr>& empires) {
	float range = GetEmpireDiplomaticRange(empire);
	EmpireUtils::GetEmpiresInRangeOfEmpire(empire, range, empires, true);
}

int cEmpireDiplomacyManager::GetEmpireAgressivity(cEmpire* empire) {
	Archetypes archetype = ArchetypeUtils::GetBaseArchetype(empire->mArchetype);
	int agressivty = baseAggressivityByArchetype[archetype];
	agressivty += aggressivityGrowthByPowerLevel[EmpireUtils::GetEmpireLevel(empire)];
	return agressivty;
}

int cEmpireDiplomacyManager::ArchetypesAffinity(Archetypes archetype1, Archetypes archetype2) {
	return archetypesAffinities[ArchetypeUtils::GetBaseArchetype(archetype1)][ArchetypeUtils::GetBaseArchetype(archetype2)];
}

int cEmpireDiplomacyManager::EmpiresAffinity(cEmpire* empire1, cEmpire* empire2) {
	int affinity = ArchetypesAffinity(empire1->mArchetype, empire2->mArchetype);
	if (DiplomacyUtils::AllianceWithAllyOfEmpire(empire1, empire2)) {
		affinity += affinityGainForAllyOfAlly;
	}
	if (DiplomacyUtils::CommonEnemy(empire1, empire2)) {
		affinity += affinityGainForEnemyOfEnemy;
	}
	if (DiplomacyUtils::AllianceWithEnemyOfEmpire(empire1, empire2) || DiplomacyUtils::AllianceWithEnemyOfEmpire(empire2, empire1)) {
		affinity += affinityGainForEnemyOfAlly;
	}
	return affinity;
}

float cEmpireDiplomacyManager::AllianceProbability(cEmpire* empire1, cEmpire* empire2) {
	int affinity = EmpiresAffinity(empire1, empire2);
	if ((affinity >= affinityThresholdForStableAlliance) || (affinity >= affinityThresholdForUnstableAlliance && DiplomacyUtils::CommonEnemy(empire1, empire2))) {
		float allianceProbability = 0.2f + (static_cast<float>(affinity - affinityThresholdForUnstableAlliance) / maxAffinitySoftCap) ;
		return min(allianceProbability, maxAllianceProbability);
	}
	else {
		return 0.0f;
	}
}

float cEmpireDiplomacyManager::BreakAllianceProbability(cEmpire* empire1, cEmpire* empire2) {
	int affinity = EmpiresAffinity(empire1, empire2);
	// If empire1 is allied with an enemy of empire2, check who they favor more based on archetype affinity.
	if (DiplomacyUtils::AllianceWithEnemyOfEmpire(empire1, empire2)) {
		eastl::set<cEmpirePtr> alliesEnemiesOfEmpire2;
		DiplomacyUtils::GetAlliesThatAreEnemiesOf(empire1, empire2, alliesEnemiesOfEmpire2);
		int archetypeAffinityWithEmpire2 = ArchetypesAffinity(empire1->mArchetype, empire2->mArchetype);
		
		for (cEmpirePtr allyEnemyOfEmpire2 : alliesEnemiesOfEmpire2) {
			int archetypeAffinityWithOtherAlly = ArchetypesAffinity(empire1->mArchetype, allyEnemyOfEmpire2->mArchetype);
			if (archetypeAffinityWithOtherAlly >= archetypeAffinityWithEmpire2) {
				return 1.0f;
			}
		}
		return 0.0f;
	}
	if ((affinity < affinityThresholdForUnstableAlliance) || (affinity < affinityThresholdForStableAlliance && !DiplomacyUtils::CommonEnemy(empire1, empire2))) {
		float breakAllianceProbability = 0.5f + (abs(static_cast<float>(affinity - affinityThresholdForUnstableAlliance)) / maxAffinitySoftCap);
		return min(breakAllianceProbability, 1.0f);
	}
	else {
		return 0.0f;
	}
}

float cEmpireDiplomacyManager::DeclareWarProbability(cEmpire* empire, cEmpire* target) {
	// Change for functions using the diplomaticProfile
	if (DiplomacyUtils::AllianceWithEnemyOfEmpire(empire, target) && autoDeclareWarOnAllyEnemies) {
		return 1.0f;
	}
	// Change for functions using the diplomaticProfile
	if (empire->mEnemies.size() != 0 && !startsWarsWhileAtWar) {
		return 0.0f;
	}
	int affinity = EmpiresAffinity(empire, target);
	if ((affinity > affinityThresholdForWar) || (affinity == affinityThresholdForWar && DiplomacyUtils::CommonEnemy(empire, target))) {
		return 0.0f;
	}
	else {
		int aggresivity = GetEmpireAgressivity(empire);
		float warProbability = static_cast<float>(aggresivity - affinity) / abs(minAffinitySoftCap);;
		return min(warProbability, maxWarProbability);
	}
}

void cEmpireDiplomacyManager::DeclareWarBetweenEmpires(cEmpire* empire1, cEmpire* empire2) {
	RelationshipManager.DeclareWar(empire1, empire2);
	auto it = diplomaticProfiles.find(empire1);
	if (it != diplomaticProfiles.end()) {
		it->second->OnWarStarted(empire2);
	}

	it = diplomaticProfiles.find(empire2);
	if (it != diplomaticProfiles.end()) {
		it->second->OnWarStarted(empire1);
	}
	/*
	auto it = diplomaticProfiles.find(empire1);
	if (it != diplomaticProfiles.end()) {
		eastl::vector<cEmpirePtr> neutrals = it->second->neutrals;
		neutrals.erase(eastl::remove(neutrals.begin(), neutrals.end(), cEmpirePtr(empire2)), neutrals.end());
		it->second->enemies.push_back(cEmpirePtr(empire2));
	}
	it = diplomaticProfiles.find(empire2);
	if (it != diplomaticProfiles.end()) {
		eastl::vector<cEmpirePtr> neutrals = it->second->neutrals;
		neutrals.erase(eastl::remove(neutrals.begin(), neutrals.end(), cEmpirePtr(empire1)), neutrals.end());
		it->second->enemies.push_back(cEmpirePtr(empire1));
	}
	*/
}

void cEmpireDiplomacyManager::DeclareAlianceBetweenEmpires(cEmpire* empire1, cEmpire* empire2) {
	RelationshipManager.DeclareAlliance(empire1, empire2);
	auto it = diplomaticProfiles.find(empire1);
	if (it != diplomaticProfiles.end()) {
		it->second->OnAllianceFormed(empire2);
	}

	it = diplomaticProfiles.find(empire2);
	if (it != diplomaticProfiles.end()) {
		it->second->OnAllianceFormed(empire1);
	}
	/*
	auto it = diplomaticProfiles.find(empire1);
	if (it != diplomaticProfiles.end()) {
		eastl::vector<cEmpirePtr> neutrals = it->second->neutrals;
		neutrals.erase(eastl::remove(neutrals.begin(), neutrals.end(), cEmpirePtr(empire2)), neutrals.end());
		it->second->allies.push_back(cEmpirePtr(empire2));
	}
	it = diplomaticProfiles.find(empire2);
	if (it != diplomaticProfiles.end()) {
		eastl::vector<cEmpirePtr> neutrals = it->second->neutrals;
		neutrals.erase(eastl::remove(neutrals.begin(), neutrals.end(), cEmpirePtr(empire1)), neutrals.end());
		it->second->allies.push_back(cEmpirePtr(empire1));
	}
	*/

}

void cEmpireDiplomacyManager::BreakAllianceBetweenEmpires(cEmpire* empire1, cEmpire* empire2) {
	RelationshipManager.BreakAlliance(empire1, empire2);
	auto it = diplomaticProfiles.find(empire1);
	if (it != diplomaticProfiles.end()) {
		it->second->OnAllianceBroken(empire2);
	}
	
	it = diplomaticProfiles.find(empire2);
	if (it != diplomaticProfiles.end()) {
		it->second->OnAllianceBroken(empire1);
	}
	it->second->OnAllianceBroken(empire1);
	/*
	auto it = diplomaticProfiles.find(empire1);
	if (it != diplomaticProfiles.end()) {
		eastl::vector<cEmpirePtr> allies = it->second->allies;
		allies.erase(eastl::remove(allies.begin(), allies.end(), cEmpirePtr(empire2)), allies.end());
	}
	it = diplomaticProfiles.find(empire2);
	if (it != diplomaticProfiles.end()) {
		eastl::vector<cEmpirePtr> allies = it->second->allies;
		allies.erase(eastl::remove(allies.begin(), allies.end(), cEmpirePtr(empire1)), allies.end());
	}
	*/
}

void  cEmpireDiplomacyManager::CreateTributeComm(cEmpire* empire) {
	CnvAction action;
	action.actionID = 0x4C182387;
	CommManager.HandleSpaceCommAction(action, empire->GetEmpireID(), empire->RequireHomePlanet()->GetID(), nullptr); //when the relation is blue face or better this doesn´t work
}

void cEmpireDiplomacyManager::ManageEmpireDiplomacy(cEmpire* empire) {
	//uint32_t playerEmpireId = SpacePlayerData::Get()->mPlayerEmpireID;

	cEmpirePtr bestAllianceTarget = nullptr;
	float bestAllianceProbability = 0.01f;

	cEmpirePtr bestBreakAllianceTarget = nullptr;
	float bestBreakAllianceProbability = 0.01f;

	cEmpirePtr bestWarTarget = nullptr;
	float bestWarProbability = 0.01f;



	//eastl::vector<cEmpirePtr> empiresInRange;
	//GetEmpiresInDiplomaticRange(empire, empiresInRange);
	eastl::vector<cEmpirePtr> empiresInRange;
	eastl::vector<cEmpirePtr> empireAllies;
	eastl::vector<cEmpirePtr> empireEnemies;
	int diplomacyRange = GetEmpireDiplomaticRange(empire);
	DiplomacyUtils::GetEmpiresInRangeByRelation(empire, diplomacyRange, empiresInRange, empireAllies, empireEnemies);
	empiresInRange.erase(
		eastl::remove_if(empiresInRange.begin(), empiresInRange.end(),
			[&](const cEmpirePtr& empire) {
				return eastl::find(empireAllies.begin(), empireAllies.end(), empire) != empireAllies.end() ||
					eastl::find(empireEnemies.begin(), empireEnemies.end(), empire) != empireEnemies.end();
			}),
		empiresInRange.end());


	int systemCountOfAlliance = EmpireUtils::GetSystemCountWithAllies(empire, empireAllies);

	for (cEmpirePtr empireInRange : empiresInRange) {
		if (empireInRange.get() == GetPlayerEmpire()) {
			continue;
		}
		// Form alliance check.
		float allianceProbability = AllianceProbability(empire, empireInRange.get());
		if (allianceProbability > bestAllianceProbability) {
			bestAllianceTarget = empireInRange;
			bestAllianceProbability = allianceProbability;
		}

		// Declare war check.
		float warProbability;
		if (DiplomacyUtils::AllianceWithEnemyOfEmpire(empire, empireInRange.get()) && autoDeclareWarOnAllyEnemies) {
			bestWarTarget = empireInRange;
			warProbability = 1.0f;
		}
		else if (empireEnemies.size() == 0 || startsWarsWhileAtWar) {
			warProbability = DeclareWarProbability(empire, empireInRange.get());
			if (warProbability > bestWarProbability) {
				if (true) { //TODO check strength of alliances
					bestWarTarget = empireInRange;
					bestWarProbability = warProbability;
				}
			}
		}
	}

	for (cEmpirePtr empireAlly : empireAllies) {
		if (empireAlly.get() == GetPlayerEmpire()) {
			continue;
		}
		// Break Alliance check.
		float breakAllianceProbability = BreakAllianceProbability(empire, empireAlly.get());
		if (breakAllianceProbability > bestBreakAllianceProbability) {
			bestBreakAllianceTarget = empireAlly;
			bestBreakAllianceProbability = breakAllianceProbability;
		}

	}

	cEmpire* playerEmpire = GetPlayerEmpire();

	if (bestAllianceTarget != nullptr) {
		RelationshipManager.DeclareAlliance(empire, bestAllianceTarget.get());
	}
	if (bestBreakAllianceTarget != nullptr) {
		RelationshipManager.BreakAlliance(empire, bestBreakAllianceTarget.get());
	}
	if (bestWarTarget != nullptr) {
		RelationshipManager.DeclareWar(empire, bestWarTarget.get());
	}

}

void cEmpireDiplomacyManager::EmpireDiplomacyCycle() {
	eastl::vector<cEmpirePtr> empires;
	EmpireUtils::GetEmpiresInRadius(GetActiveStarRecord()->mPosition, activeRadius, empires);
	diplomaticProfiles.clear();
	for (cEmpirePtr empire : empires) {
		if (EmpireUtils::ValidNpcEmpire(empire.get())) {
			cDiplomaticProfile * diplomaticProfile = new cDiplomaticProfile(empire.get());
			diplomaticProfiles[empire] = cDiplomaticProfilePtr(diplomaticProfile);
		}
	}
	// TODO the alliance strenght.
	for (auto pair : diplomaticProfiles) {
		if (EmpireUtils::ValidNpcEmpire(pair.first.get())) {
			cEmpirePtr empire = pair.first;
			cDiplomaticProfilePtr diplomacyProfile = pair.second;
			cEmpire* breakAllianceTarget = diplomacyProfile->GetBreakAllianceTarget();
			if (breakAllianceTarget != nullptr) {
				BreakAllianceBetweenEmpires(empire.get(), breakAllianceTarget);
			}

			cEmpire* warTarget = diplomacyProfile->GetWarTarget();
			if (warTarget != nullptr) {
				DeclareWarBetweenEmpires(empire.get(), warTarget);
			}

			cEmpire* allianceTarget = diplomacyProfile->GetAllianceTarget();
			if (allianceTarget != nullptr) {
				DeclareAlianceBetweenEmpires(empire.get(), allianceTarget);
			}
		}
	}
}
