#include "stdafx.h"
#include "cWarfareSystem.h"
#include "cPlanetAttackedEvent.h"
#include "cToolInvasionStrategy.h"
#include <Spore-Mod-Utils/Include/SporeModUtils.h>
using namespace SporeModUtils;
using namespace Simulator;

cWarfareSystem* cWarfareSystem::instance = nullptr;

/// AUTOGENERATED METHODS ///

int cWarfareSystem::AddRef() {
	return Simulator::cStrategy::AddRef();
}
int cWarfareSystem::Release() {
	return Simulator::cStrategy::Release();
}

const char* cWarfareSystem::GetName() const {
	return "Ai_Empire_Diplomacy::cWarfareSystem";
}

bool cWarfareSystem::Write(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cWarfareSystem::Read(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cWarfareSystem::ATTRIBUTES[] = {
	// Add more attributes here
	// This one must always be at the end
	Simulator::Attribute()
};

void cWarfareSystem::Initialize() {
	instance = this;
	ready = false;

	PropertyListPtr managerConfigProp;

	PropManager.GetPropertyList(id("ManagerConfig"), id("SwoConfig"), managerConfigProp);

	App::Property::GetInt32(managerConfigProp.get(), 0x86C25CEA, cycleInterval);
	App::Property::GetInt32(managerConfigProp.get(), 0x9EC13ACD, minSubcycleStep);
	App::Property::GetFloat(managerConfigProp.get(), 0x0D00F9E5, activeRadius);

	empireWarfareFactory = nullptr;
	elapsedTime = 0;
	subcycleStep = 0;
	empiresPerSubCycle = 0;
	nextSubcycleTime = 0;
	cycle = 0;
	
}

void cWarfareSystem::Dispose() {
	
}

void cWarfareSystem::Update(int deltaTime, int deltaGameTime) {
	if (IsSpaceGame() && ready) {
		elapsedTime += deltaGameTime;
		if (elapsedTime > cycleInterval) {
			StartWarfareCycle();
			cycle++;
		}
		// Start of a subcycle.
		while (elapsedTime > nextSubcycleTime) {
			WarfareSubCycle();
			nextSubcycleTime += subcycleStep;
		}
	}
}

void cWarfareSystem::OnModeEntered(uint32_t previousModeID, uint32_t newModeID) {
	if (newModeID == GameModeIDs::kGameSpace) {
		empiresWarfare.clear();

		// Randomizes the start of the first cycle to avoid being synchronized with the cycles of other managers.
		elapsedTime = Math::rand(cycleInterval / 2);
		nextSubcycleTime = 9999999;
		cycle = 0;
	}
}

void cWarfareSystem::OnModeExited(uint32_t previousModeID, uint32_t newModeID) {
	if (previousModeID == GameModeIDs::kGameSpace) {
		empiresWarfare.clear();
		empireWarfareFactory.reset();
		ready = false;
	}
}

bool cWarfareSystem::WriteToXML(XmlSerializer*)
{
	return true;
}

cWarfareSystem* cWarfareSystem::Get() {
	return instance;
}

void cWarfareSystem::InjectDependencies(cEmpireWarfareFactory* empireWarfareFactory){
	this->empireWarfareFactory = empireWarfareFactory;
	ready = true;
}

void cWarfareSystem::WarfareSubCycle() {
	if (empireToManage != empiresWarfare.end()) {
		if (EmpireUtils::ValidNpcEmpire(empireToManage->get()->empire.get())) {
			empireToManage->get()->SelectAndAttackTargets();
		}
		++empireToManage;
	}
}

void cWarfareSystem::StartWarfareCycle() {
	empiresWarfare.clear();

	eastl::vector<cEmpirePtr> empires;
	EmpireUtils::GetEmpiresInRadius(GetPlayerHomePlanet()->GetStarRecord()->mPosition, activeRadius, empires);
	for (cEmpirePtr empire : empires) {
		if (EmpireUtils::ValidNpcEmpire(empire.get())) {
			cEmpireWarfarePtr empireDiplomacy = empireWarfareFactory->CreateEmpireWarfare(empire.get());
			empiresWarfare.push_back(empireDiplomacy);
		}
	}
	
	empireToManage = empiresWarfare.begin();
	int numEmpires = empiresWarfare.size();
	int calculatedStep = cycleInterval / (numEmpires + 1);
	subcycleStep = max(calculatedStep, minSubcycleStep);
	// substract subcycleStep because the first subcycle is at subcycleStep miliseconds.
	int numSubcycles = cycleInterval / subcycleStep;
	// Division rounding up.
	empiresPerSubCycle = (numEmpires + numSubcycles - 1) / (numSubcycles);
	elapsedTime = 0;
	nextSubcycleTime = subcycleStep;
}